apiVersion: v1
kind: ReplicationController
metadata:
  name: auth-layer
spec:
  selector:
    name: web
    version: v0.1
  template:
    metadata:
      labels:
        name: web
        version: v0.1
    spec:
      containers:
      - name: auth-layer
        image: gummadic/auth-layer:1.0.0
        ports:
        - containerPort: 5000