apiVersion: v1
kind: ReplicationController
metadata:
  name: data-layer
spec:
  selector:
    name: web
    version: v0.1
  template:
    metadata:
      labels:
        name: web
        version: v0.1
    spec:
      containers:
      - name: data-layer
        image: gummadic/data-layer:v1
        ports:
        - containerPort: 5000